CREATE TABLE "ADUSER"."AD_USER" 
   (	
    
	PW VARCHAR2(20 BYTE), 
    name  VARCHAR2(15)  ,
    TLPHON_NO	 VARCHAR2(15)  ,
    MBTLNUM	 VARCHAR2(15)  ,
	GRAD VARCHAR2(5 BYTE),
    ATPT	 VARCHAR2(2)   ,
 	GU_GUN	 VARCHAR2(5)   ,
 	DETAIL_ADRES	 VARCHAR2(100)  ,
    RPRSNTV_ID VARCHAR2(20 BYTE),
    USE_YN	 VARCHAR2(1)   
   ) 
  TABLESPACE "TS_DEV_AD" ;

COMMENT ON COLUMN AD_USER.id IS 'ID';
COMMENT ON COLUMN AD_USER.PW IS 'PW';
COMMENT ON COLUMN AD_USER.name IS '이름';
COMMENT ON COLUMN AD_USER.TLPHON_NO IS '전화번호';
COMMENT ON COLUMN AD_USER.MBTLNUM IS '휴대폰번호';
COMMENT ON COLUMN AD_USER.GRAD IS '등급';
COMMENT ON COLUMN AD_USER.ATPT IS '시도코드';
COMMENT ON COLUMN AD_USER.GU_GUN IS '구군코드';
COMMENT ON COLUMN AD_USER.DETAIL_ADRES IS '상세주소';
COMMENT ON COLUMN AD_USER.RPRSNTV_ID IS '대표자ID';
COMMENT ON COLUMN AD_USER.USE_YN IS '사용여부';
COMMENT ON TABLE AD_USER IS '사용자';

CREATE TABLE ADVRTS_ENTRPS_INFO 
(
 	 ADVRTS_ENTRPS_ID	 VARCHAR2(20)  ,
	 ADVRTS_ENTRPS_NM	 VARCHAR2(100) ,
 	 RPRSNTV_NM	 VARCHAR2(15)  ,
 	 ADVRTS_ENTRPS_BIZRNO	 VARCHAR2(20)  ,
	 ENTRPS_TLPHON_NO	 VARCHAR2(15)  ,
 	 ENTRPS_MBTLNUM	 VARCHAR2(15)  ,
 	 ENTRPS_ATPT	 VARCHAR2(2)   ,
 	 ENTRPS_GU_GUN	 VARCHAR2(5)   ,
 	 ENTRPS_DETAIL_ADRES	 VARCHAR2(100)  ,
     QR_FILE_ID	 VARCHAR2(50)  ,
 	 USE_YN	 VARCHAR2(1)
)  TABLESPACE "TS_DEV_AD" ;

COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ADVRTS_ENTRPS_ID IS '광고업체ID';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ADVRTS_ENTRPS_NM IS '광고업체명';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.RPRSNTV_NM IS '광고대표자명';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ADVRTS_ENTRPS_BIZRNO IS '점포사업자번호';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ENTRPS_TLPHON_NO IS '업체전화번호';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ENTRPS_MBTLNUM IS '업체휴대폰번호';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ENTRPS_ATPT IS '광고업체주소(시도)';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ENTRPS_GU_GUN IS '광고업체주소(구군)';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.ENTRPS_DETAIL_ADRES IS '광고업체상세주소';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.QR_FILE_ID IS 'QR파일ID';
COMMENT ON COLUMN ADVRTS_ENTRPS_INFO.USE_YN IS '이용여부';
COMMENT ON TABLE ADVRTS_ENTRPS_INFO IS '광고업체정보';

CREATE TABLE STOR_MNG (
 	 STOR_ID	 VARCHAR2(20)  NOT NULL ,
 	 ADVRTS_ENTRPS_ID	 VARCHAR2(20)  NOT NULL ,
 	 STOR_NM	 VARCHAR2(100)   ,
 	 STOR_RPRSNTV_NM	 VARCHAR2(50)   ,
 	 STOR_BIZRNO	 VARCHAR2(10)   ,
 	 STOR_TLPHON_NO	 VARCHAR2(15)   ,
 	 STOR_MBTLNUM	 VARCHAR2(15)   ,
 	 FILE_ID	 VARCHAR2(50)   ,
 	 STOR_INDUTY	 VARCHAR2(10)   ,
 	 EXPSR_PRIORT	 NUMBER(4)   ,
 	 STOR_ADRES	 VARCHAR2(100)   ,
 	 STOR_DETAIL_ADRES	 VARCHAR2(100)   ,
 	 EXPSR_TLPHON_NO	 VARCHAR2(15)   
)  TABLESPACE "TS_DEV_AD" ;

COMMENT ON COLUMN STOR_MNG.STOR_ID IS '점포ID';
COMMENT ON COLUMN STOR_MNG.ADVRTS_ENTRPS_ID IS '광고업체ID';
COMMENT ON COLUMN STOR_MNG.STOR_NM IS '점포명';
COMMENT ON COLUMN STOR_MNG.STOR_RPRSNTV_NM IS '점포대표명';
COMMENT ON COLUMN STOR_MNG.STOR_BIZRNO IS '점포사업자번호';
COMMENT ON COLUMN STOR_MNG.STOR_TLPHON_NO IS '점포전화번호';
COMMENT ON COLUMN STOR_MNG.STOR_MBTLNUM IS '점포휴대전화';
COMMENT ON COLUMN STOR_MNG.FILE_ID IS '파일ID';
COMMENT ON COLUMN STOR_MNG.STOR_INDUTY IS '점포업종';
COMMENT ON COLUMN STOR_MNG.EXPSR_PRIORT IS '노출우선순위';
COMMENT ON COLUMN STOR_MNG.STOR_ADRES IS '점포주소';
COMMENT ON COLUMN STOR_MNG.STOR_DETAIL_ADRES IS '점포상세주소';
COMMENT ON COLUMN STOR_MNG.EXPSR_TLPHON_NO IS '노출 전화번호';
COMMENT ON TABLE STOR_MNG IS '점포관리';

CREATE TABLE FILE_MNG (
 	 FILE_ID	 VARCHAR2(20)   ,
 	 FILE_SE	 VARCHAR2(3)   ,
 	 ORGINL_FILE_NM	 VARCHAR2(50)   ,
 	 FILE_NM	 VARCHAR2(20)   ,
 	 FLPTH	 VARCHAR2(100)   
)  TABLESPACE "TS_DEV_AD" ;

COMMENT ON COLUMN FILE_MNG.FILE_ID IS '파일ID';
COMMENT ON COLUMN FILE_MNG.FILE_SE IS '파일구분';
COMMENT ON COLUMN FILE_MNG.ORGINL_FILE_NM IS '원본파일명';
COMMENT ON COLUMN FILE_MNG.FILE_NM IS '파일명';
COMMENT ON COLUMN FILE_MNG.FLPTH IS '파일경로';
COMMENT ON TABLE FILE_MNG IS '파일관리';

CREATE TABLE ADVRTS_ENTRPS_CNTRCT_MNG (
 	 CNTRCT_SEQ	 NUMBER NOT NULL ,
 	 ADVRTS_ENTRPS_ID	 VARCHAR2(20)  NOT NULL ,
 	 BEGIN_DATE	 DATE  ,
 	 END_DATE	 DATE  ,
 	 RCPMNY_DATE	 DATE  ,
 	 RCPMNYER	 VARCHAR2(50)   ,
 	 RCPMNY_AMOUNT	 NUMBER  ,
 	 CNTRCT_AMOUNT	 NUMBER  ,
 	 PURCHASE_AMOUNT	 NUMBER  
)  TABLESPACE "TS_DEV_AD" ;
CREATE SEQUENCE SEQ_CNTRCT_SEQ
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE NOCACHE;
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.CNTRCT_SEQ IS '계약_SEQ';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.ADVRTS_ENTRPS_ID IS '광고업체ID';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.BEGIN_DATE IS '시작일자';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.END_DATE IS '종료일자';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.RCPMNY_DATE IS '입금일자';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.RCPMNYER IS '입금자';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.RCPMNY_AMOUNT IS '입금금액';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.CNTRCT_AMOUNT IS '계약금액';
COMMENT ON COLUMN ADVRTS_ENTRPS_CNTRCT_MNG.PURCHASE_AMOUNT IS '미입금액';
COMMENT ON TABLE ADVRTS_ENTRPS_CNTRCT_MNG IS '광고업체계약관리';

CREATE TABLE STOR_CNTRCT_MNG (
 	 STORE_SEQ	 NUMBER  ,
 	 STORE_ID	 VARCHAR2(20)   ,
 	 BEGIN_DATE	 DATE  ,
 	 END_DATE	 DATE  ,
 	 RCPMNY_DATE	 DATE  ,
 	 RCPMNYER	 VARCHAR2(20)   ,
 	 RCPMNY_AMOUNT	 NUMBER  ,
 	 CNTRCTAMOUNT	 NUMBER  ,
 	 PURCHASE_AMOUNT	 NUMBER  
)  TABLESPACE "TS_DEV_AD" ;

COMMENT ON COLUMN STOR_CNTRCT_MNG.STORE_SEQ IS '점포계약SEQ';
COMMENT ON COLUMN STOR_CNTRCT_MNG.STORE_ID IS '점포ID';
COMMENT ON COLUMN STOR_CNTRCT_MNG.BEGIN_DATE IS '시작일자';
COMMENT ON COLUMN STOR_CNTRCT_MNG.END_DATE IS '종료일자';
COMMENT ON COLUMN STOR_CNTRCT_MNG.RCPMNY_DATE IS '입금일자';
COMMENT ON COLUMN STOR_CNTRCT_MNG.RCPMNYER IS '입금자';
COMMENT ON COLUMN STOR_CNTRCT_MNG.RCPMNY_AMOUNT IS '입금금액';
COMMENT ON COLUMN STOR_CNTRCT_MNG.CNTRCTAMOUNT IS '계약금액';
COMMENT ON COLUMN STOR_CNTRCT_MNG.PURCHASE_AMOUNT IS '미입금액';
COMMENT ON TABLE STOR_CNTRCT_MNG IS '점포계약관리';

CREATE TABLE MP_BOARD(
    BNO NUMBER NOT NULL,
    TITLE VARCHAR2(100)     NOT NULL,
    CONTENT VARCHAR2(2000)  NOT NULL,
    WRITER VARCHAR2(100)    NOT NULL,
    REGDATE DATE            DEFAULT SYSDATE,
    PRIMARY KEY(BNO)
)TABLESPACE "TS_DEV_AD";

COMMENT ON COLUMN MP_BOARD.BNO IS '게시판 번호';
COMMENT ON COLUMN MP_BOARD.TITLE IS '게시판 제목';
COMMENT ON COLUMN MP_BOARD.CONTENT IS '게시판 내용';
COMMENT ON COLUMN MP_BOARD.WRITER IS '작성자';
COMMENT ON COLUMN MP_BOARD.REGDATE IS '등록일';
COMMENT ON TABLE MP_BOARD IS '게시판';

 
 CREATE SEQUENCE MP_BOARD_SEQ START WITH 0 MINVALUE 0;
 
 create table mp_reply (
    bno number not null,
    rno number not null,
    content varchar2(1000) not null,
    writer varchar2(50) not null,
    regdate date default sysdate,
    primary key(bno, rno)
)TABLESPACE "TS_DEV_AD";

alter table mp_reply add constraint mp_reply_bno foreign key(bno)
references mp_board(bno);

create sequence mp_reply_seq START WITH 1 MINVALUE 0;

INSERT INTO MP_BOARD(BNO, TITLE, CONTENT, WRITER)
     VALUES (MP_BOARD_SEQ.NEXTVAL, '제목입니다', '내용입니다', 'MELONPEACH');
     
insert into mp_reply(bno, rno, content, writer)
    values(4, mp_reply_seq.nextval, '테스트댓글', '테스트 작성자');

select rno, content, writer, regdate
  from mp_reply
 where bno = 0;
 
 
 SELECT
    count(*)
    	 FROM MP_BOARD
         
;
CREATE TABLE MP_FILE
(
    FILE_NO NUMBER,                         --파일 번호
    BNO NUMBER NOT NULL,                    --게시판 번호
    ORG_FILE_NAME VARCHAR2(260) NOT NULL,   --원본 파일 이름
    STORED_FILE_NAME VARCHAR2(36) NOT NULL, --변경된 파일 이름
    FILE_SIZE NUMBER,                       --파일 크기
    REGDATE DATE DEFAULT SYSDATE NOT NULL,  --파일등록일
    DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL,--삭제구분
    PRIMARY KEY(FILE_NO)                    --기본키 FILE_NO
)TABLESPACE "TS_DEV_AD";

COMMENT ON COLUMN MP_FILE.FILE_NO IS '파일 번호';
COMMENT ON COLUMN MP_FILE.BNO IS '게시판 번호';
COMMENT ON COLUMN MP_FILE.ORG_FILE_NAME IS '원본 파일 이름';
COMMENT ON COLUMN MP_FILE.STORED_FILE_NAME IS '변경된 파일 이름';
COMMENT ON COLUMN MP_FILE.FILE_SIZE IS '파일 크기';
COMMENT ON COLUMN MP_FILE.REGDATE IS '파일등록일';
COMMENT ON COLUMN MP_FILE.DEL_GB IS '삭제구분';
COMMENT ON TABLE MP_FILE IS '파일관리';

CREATE SEQUENCE SEQ_MP_FILE_NO
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE NOCACHE;

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) ,
	JOB_NAME VARCHAR2(100 char) NOT NULL,
	JOB_KEY VARCHAR2(32 char) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
)TABLESPACE "TS_DEV_AD";

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0)  ,
	JOB_INSTANCE_ID NUMBER(19,0) NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10 char) ,
	EXIT_CODE VARCHAR2(2500 char) ,
	EXIT_MESSAGE VARCHAR2(2500 char) ,
	LAST_UPDATED TIMESTAMP,
	JOB_CONFIGURATION_LOCATION VARCHAR(2500 char) NULL,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
)TABLESPACE "TS_DEV_AD";

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL ,
	TYPE_CD VARCHAR2(6 char) NOT NULL ,
	KEY_NAME VARCHAR2(100 char) NOT NULL ,
	STRING_VAL VARCHAR2(250 char) ,
	DATE_VAL TIMESTAMP DEFAULT NULL ,
	LONG_VAL NUMBER(19,0) ,
	DOUBLE_VAL NUMBER ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)TABLESPACE "TS_DEV_AD";

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID NUMBER(19,0)  NOT NULL PRIMARY KEY ,
	VERSION NUMBER(19,0) NOT NULL,
	STEP_NAME VARCHAR2(100 char) NOT NULL,
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
	START_TIME TIMESTAMP NOT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR2(10 char) ,
	COMMIT_COUNT NUMBER(19,0) ,
	READ_COUNT NUMBER(19,0) ,
	FILTER_COUNT NUMBER(19,0) ,
	WRITE_COUNT NUMBER(19,0) ,
	READ_SKIP_COUNT NUMBER(19,0) ,
	WRITE_SKIP_COUNT NUMBER(19,0) ,
	PROCESS_SKIP_COUNT NUMBER(19,0) ,
	ROLLBACK_COUNT NUMBER(19,0) ,
	EXIT_CODE VARCHAR2(2500 char) ,
	EXIT_MESSAGE VARCHAR2(2500 char) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)TABLESPACE "TS_DEV_AD";

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500 char) NOT NULL,
	SERIALIZED_CONTEXT CLOB ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
)TABLESPACE "TS_DEV_AD";

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR2(2500 char) NOT NULL,
	SERIALIZED_CONTEXT CLOB ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
)TABLESPACE "TS_DEV_AD";

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;

select * from BATCH_JOB_INSTANCE
;
SELECT  * FROM BATCH_JOB_EXECUTION
;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS
;
SELECT * FROM BATCH_STEP_EXECUTION
;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT
;
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT
;
insert into  ADVRTS_ENTRPS_INFO (ID, ADVRTS_ENTRPS_ID, FILE_ID, ADVRTS_ENTRPS_NM,
	 TLPHON_NO, MBTLNUM, ATPT, GU_GUN, DETAIL_ADRES, USE_YN, RPRSNTV_NM, ADVRTS_ENTRPS_BIZRNO)VALUES
     ('A002','AD002','FILE_ID','광고업체B',
     '02-2222-2222', '010-2222-2222','02', '02', '경인로', 'Y', '광고주B', '11'
     );
insert into  ADVRTS_ENTRPS_CNTRCT_MNG(CNTRCT_SEQ,ADVRTS_ENTRPS_ID, BEGIN_DATE, end_date, rcpmny_date
, rcpmnyer, cntrct_amount, rcpmny_amount, purchase_amount)
VALUES(SEQ_CNTRCT_SEQ.nextval,'AD002', to_date('20190101','yyyymmdd'),to_date('20201231','yyyymmdd')
,to_date('20190101','yyyymmdd'),'광고주B', 20000, 20000 , 20000)
;
CREATE TABLE ADUSER.COMMON_CODE(	
    GRP_CODE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
    CODE VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	CODE_NM VARCHAR2(100 BYTE), 
    CODE_DSCR VARCHAR2(100 BYTE), 
    PARENT_CODE  VARCHAR2(5)  ,
    CODE_PRPR1	 VARCHAR2(15)  ,
    CODE_PRPR2	 VARCHAR2(15)  ,
    USE_YN	 VARCHAR2(1)   
   ) TABLESPACE TS_DEV_AD;
  
COMMENT ON COLUMN COMMON_CODE.GRP_CODE IS '그룹코드';
COMMENT ON COLUMN COMMON_CODE.CODE IS '코드';
COMMENT ON COLUMN COMMON_CODE.CODE_NM IS '코드명';
COMMENT ON COLUMN COMMON_CODE.CODE_DSCR IS '코드설명';
COMMENT ON COLUMN COMMON_CODE.PARENT_CODE IS '상위코드';
COMMENT ON COLUMN COMMON_CODE.CODE_PRPR1 IS '코드속성1';
COMMENT ON COLUMN COMMON_CODE.CODE_PRPR2 IS '코드속성2';
COMMENT ON COLUMN COMMON_CODE.USE_YN IS '사용여부';
COMMENT ON TABLE COMMON_CODE IS '공통코드';

CREATE TABLE ADUSER.USER_MPNG(	
    ID VARCHAR2(20 BYTE), 
    ADVRTS_ENTRPS_ID VARCHAR2(20)  
   ) TABLESPACE TS_DEV_AD;
   
COMMENT ON COLUMN USER_MPNG.ID IS 'ID';
COMMENT ON COLUMN USER_MPNG.ADVRTS_ENTRPS_ID IS '광고업체ID';
COMMENT ON TABLE USER_MPNG IS '사용자맵핑';   